site:
  name: Project Fitcare
  site: 'https://projectfitcare.com.au'
  base: '/'
  trailingSlash: false

# Default SEO metadata
metadata:
  title:
    default: Project Fitcare
    template: '%s — Project Fitcare'
  description: 'NDIS fitness support that delivers real, tangible outcomes through practical hands-on care. Project Fitcare helps you stay active, healthy, and independent.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Project Fitcare
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6

    post:
      isEnabled: false
      permalink: '/%slug%'
      robots:
        index: false

    list:
      isEnabled: false
      pathname: 'blog'
      robots:
        index: false

    category:
      isEnabled: false
      pathname: 'category'
      robots:
        index: false

    tag:
      isEnabled: false
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: false
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'light'
